In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.patches import Patch
import matplotlib.colors as mcolors
from scipy import stats
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
import statsmodels.api as sm

whiteouts = pd.read_csv('white_out_plays.csv')
whiteouts

,season,week,pff_game_id,pff_play_id,sort_order,quarter,time_left_in_game,time_left_in_half,two_minute,play_clock,...,yards_after_catch,pressure,sack,time_to_pressure,pass_breakup,primary_run_concept,intended_poa,actual_poa,missed_tackle,yards_after_contact
0,2025,5,29087,6526783,1,1,3600,1800,0,NaN,...,NaN,0,0,NaN,0,NaN,NaN,NaN,0,NaN
1,2025,5,29087,6526867,2,1,3600,1800,0,8.0,...,NaN,0,0,NaN,0,OUTSIDE ZONE,ML,ML,0,2.0
2,2025,5,29087,6527221,3,1,3571,1771,0,21.0,...,0.0,0,0,NaN,0,NaN,NaN,NaN,0,0.0
3,2025,5,29087,6527227,4,1,3541,1741,0,13.0,...,NaN,0,0,NaN,0,FB RUN,ML,ML,0,0.0
4,2025,5,29087,6527230,5,1,3501,1701,0,11.0,...,7.0,1,0,1.9,0,OUTSIDE ZONE,NaN,NaN,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
829,2024,11,26842,6086422,148,4,91,91,0,20.0,...,1.0,0,0,NaN,0,NaN,NaN,NaN,0,0.0
830,2024,11,26842,6086437,149,4,88,88,0,15.0,...,NaN,0,0,NaN,0,OUTSIDE ZONE,LE,LE,0,1.0
831,2024,11,26842,6086451,150,4,74,74,0,9.0,...,NaN,0,0,NaN,0,INSIDE ZONE,RT,RT,0,1.0
832,2024,11,26842,6086463,151,4,49,49,0,25.0,...,NaN,0,0,NaN,0,MAN,MR,MR,0,1.0
833,2024,11,26842,6086471,152,4,14,14,0,16.0,...,NaN,0,0,NaN,0,OUTSIDE ZONE,MR,LG,0,1.0

In [4]:
final_scores = whiteouts.groupby('pff_game_id').last().reset_index()[['pff_game_id', 'offense', 'defense', 'off_score', 'def_score']]
final_scores

   pff_game_id offense defense  off_score  def_score
0        20142    ALAU    PAST         20         28
1        22087    MNUN    PAST         17         45
2        24378    PAST    IAUN         31          0
3        26842    PAST    WAUN         35          6
4        29087    PAST    ORUN         24         30

In [6]:
whiteouts['pff_game_id'].unique()

array([29087, 20142, 22087, 24378, 26842])